steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/mlflow'
      - '-f'
      - 'docker/mlflow/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/prefect'
      - '-f'
      - 'docker/prefect/Dockerfile'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/mlflow'
  - '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/prefect'