name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Start Cloud SQL Auth Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCP_SA_KEY }}
          instance: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg

      - name: Grant DB privileges to mlflow_user & prefect_user
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          # mlflow_user on mlflow_db
          psql -h 127.0.0.1 -U postgres -c "GRANT CONNECT ON DATABASE mlflow_db TO mlflow_user;"
          psql -h 127.0.0.1 -U postgres -d mlflow_db \
            -c "GRANT USAGE ON SCHEMA public TO mlflow_user;"
          psql -h 127.0.0.1 -U postgres -d mlflow_db \
            -c "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mlflow_user;"

          # prefect_user on prefect_db
          psql -h 127.0.0.1 -U postgres -c "GRANT CONNECT ON DATABASE prefect_db TO prefect_user;"
          psql -h 127.0.0.1 -U postgres -d prefect_db \
            -c "GRANT USAGE ON SCHEMA public TO prefect_user;"
          psql -h 127.0.0.1 -U postgres -d prefect_db \
            -c "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO prefect_user;"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push mlflow
        run: |
          docker build \
            --file docker/mlflow/Dockerfile \
            --tag ${{ secrets.ARTIFACT_REGISTRY }}/mlflow:latest \
            docker/mlflow
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/mlflow:latest

      - name: Build & Push prefect
        run: |
          docker build \
            --file docker/prefect-agent/Dockerfile \
            --tag ${{ secrets.ARTIFACT_REGISTRY }}/prefect:latest \
            docker/prefect-agent
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/prefect:latest

      - name: Deploy MLflow Server to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service:             mlflow-server
          image:               ${{ secrets.ARTIFACT_REGISTRY }}/mlflow:latest
          region:              ${{ secrets.GCP_REGION }}
          project_id:          ${{ secrets.GCP_PROJECT }}
          service_account:     github-actions-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com
          vpc_connector:       vpc-connector
          cloud_sql_instances: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg
          env_vars: |
            MLFLOW_TRACKING_URI=postgresql+psycopg2://mlflow_user:${{ secrets.DB_PASSWORD }}@/mlflow_db?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg
            ARTIFACT_BUCKET=${{ secrets.ARTIFACT_BUCKET }}

      - name: Deploy Prefect Agent to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service:             prefect-agent
          image:               ${{ secrets.ARTIFACT_REGISTRY }}/prefect:latest
          region:              ${{ secrets.GCP_REGION }}
          project_id:          ${{ secrets.GCP_PROJECT }}
          service_account:     github-actions-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com
          vpc_connector:       vpc-connector
          cloud_sql_instances: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg
          env_vars: |
            PREFECT_ORION_UI_API_URL=https://mlflow-server-${{ secrets.GCP_REGION }}.run.app
            PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect_user:${{ secrets.PREFECT_PASSWORD }}@/prefect_db?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg