name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'src/**'
      - '.github/workflows/deploy.yml'
  workflow_run:
    workflows: [ 'Terraform' ]
    types: [ completed ]
    
permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT:     ${{ secrets.GCP_PROJECT }}
  GCP_REGION:      ${{ secrets.GCP_REGION }}
  ARTIFACT_REPO:   mlops-docker
  ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_BUCKET }}
  DB_INSTANCE:     "${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build & Push Images
        run: |
            gcloud builds submit . \
          --config cloudbuild.yaml \
          --substitutions=_REGION=$GCP_REGION,_PROJECT=$GCP_PROJECT,_REPO=$ARTIFACT_REPO

      - name: Deploy MLflow Server
        run: |
          gcloud run deploy mlflow-server \
            --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/$ARTIFACT_REPO/mlflow \
            --region $GCP_REGION \
            --platform managed \
            --vpc-connector mlops-vpc \
            --add-cloudsql-instances $DB_INSTANCE \
            --set-env-vars "MLFLOW_TRACKING_URI=postgresql+psycopg2://mlflow_user:${{ secrets.DB_PASSWORD }}@/mlflow_db?host=/cloudsql/$DB_INSTANCE,ARTIFACT_BUCKET=$ARTIFACT_BUCKET"

      - name: Deploy Prefect Agent
        run: |
          gcloud run deploy prefect-agent \
            --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/$ARTIFACT_REPO/prefect \
            --region $GCP_REGION \
            --platform managed \
            --vpc-connector mlops-vpc \
            --add-cloudsql-instances $DB_INSTANCE \
            --set-env-vars "PREFECT_ORION_UI_API_URL=https://mlflow-server-$GCP_REGION.run.app,PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect_user:${{ secrets.PREFECT_PASSWORD }}@/prefect_db?host=/cloudsql/$DB_INSTANCE"
