name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push mlflow
        run: |
          docker build \
            --file docker/mlflow/Dockerfile \
            --tag ${{ secrets.ARTIFACT_REGISTRY }}/mlflow:latest \
            .
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/mlflow:latest

      - name: Build & Push prefect
        run: |
          docker build \
            --file docker/prefect-agent/Dockerfile \
            --tag ${{ secrets.ARTIFACT_REGISTRY }}/prefect:latest \
            .
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/prefect:latest

      - name: Deploy MLflow Server to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mlflow-server
          image: ${{ secrets.ARTIFACT_REGISTRY }}/mlflow:latest
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account: github-actions-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com
          vpc_connector: vpc-connector
          cloud_sql_instances: ${{ secrets.GCP_PROJECT }}:europe-west2:mlflow-pg
          env_vars: |
            MLFLOW_TRACKING_URI=postgresql+psycopg2://mlflow_user:${{ secrets.DB_PASSWORD }}@/mlflow_db?host=/cloudsql/${{ secrets.GCP_PROJECT }}:europe-west2:mlflow-pg
            ARTIFACT_BUCKET=${{ secrets.ARTIFACT_BUCKET }}

      - name: Deploy Prefect Agent to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: prefect-agent
          image: ${{ secrets.ARTIFACT_REGISTRY }}/prefect:latest
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account: github-actions-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com
          vpc_connector: vpc-connector
          cloud_sql_instances: ${{ secrets.GCP_PROJECT }}:europe-west2:mlflow-pg
          env_vars: |
            PREFECT_ORION_UI_API_URL=https://mlflow-server-europe-west2.run.app
            PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect_user:${{ secrets.PREFECT_PASSWORD }}@/prefect_db?host=/cloudsql/${{ secrets.GCP_PROJECT }}:europe-west2:mlflow-pg
