permissions:
  contents: read
  id-token: write

name: Build & Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auth-setup:
    name: Authenticate to GCP & Expose Registry
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.set-reg.outputs.registry }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        uses: google-github-actions/configure-docker@v1
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Expose registry URL
        id: set-reg
        run: |
          echo "registry=${{ secrets.ARTIFACT_REGISTRY }}" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build & Push Images
    needs: auth-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build MLflow image
        run: |
          docker build \
            --file docker/mlflow/Dockerfile \
            --tag mlflow:latest \
            .
          docker tag mlflow:latest \
            ${{ needs.auth-setup.outputs.registry }}/mlflow:latest

      - name: Push MLflow image
        run: |
          docker push ${{ needs.auth-setup.outputs.registry }}/mlflow:latest

      - name: Build Prefect-Agent image
        run: |
          docker build \
            --file docker/prefect-agent/Dockerfile \
            --tag prefect-agent:latest \
            .
          docker tag prefect-agent:latest \
            ${{ needs.auth-setup.outputs.registry }}/prefect-agent:latest

      - name: Push Prefect-Agent image
        run: |
          docker push ${{ needs.auth-setup.outputs.registry }}/prefect-agent:latest

  deploy-cloud-run:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy MLflow Server
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mlflow-server
          image: ${{ needs.auth-setup.outputs.registry }}/mlflow:latest
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          env_vars: |
            ARTIFACT_BUCKET=${{ secrets.ARTIFACT_BUCKET }}

      - name: Deploy Prefect Agent
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: prefect-agent
          image: ${{ needs.auth-setup.outputs.registry }}/prefect-agent:latest
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          env_vars: |
            PREFECT_ORION_URL=https://mlflow-server-${{ secrets.GCP_REGION }}.run.app