name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  auth-setup:
    name: Install & Authenticate gcloud
    runs-on: ubuntu-latest
    outputs:
      registry_host: ${{ steps.set-reg.outputs.registry_host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker \
            ${{ secrets.GCP_REGION }}-docker.pkg.dev \
            --quiet

      - id: set-reg
        name: Expose registry host
        run: |
          echo "registry_host=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}" \
            >> $GITHUB_OUTPUT

  build-and-push:
    name: Build & Push Docker Images
    needs: auth-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Push mlflow image
        run: |
          docker build \
            --file docker/mlflow/Dockerfile \
            --tag mlflow:latest \
            .
          docker tag mlflow:latest \
            ${{ needs.auth-setup.outputs.registry_host }}/mlflow/mlflow:latest
          docker push \
            ${{ needs.auth-setup.outputs.registry_host }}/mlflow/mlflow:latest

      - name: Build & Push prefect-agent image
        run: |
          docker build \
            --file docker/prefect-agent/Dockerfile \
            --tag prefect-agent:latest \
            .
          docker tag prefect-agent:latest \
            ${{ needs.auth-setup.outputs.registry_host }}/prefect/prefect-agent:latest
          docker push \
            ${{ needs.auth-setup.outputs.registry_host }}/prefect/prefect-agent:latest

  deploy-cloud-run:
    name: Deploy to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy MLflow Server
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: mlflow-server
          image: ${{ needs.auth-setup.outputs.registry_host }}/mlflow/mlflow:latest
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account: github-actions-sa@mlops-461322.iam.gserviceaccount.com
          vpc_connector: vpc-connector
          cloud_sql_instances: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg
          env_vars: |
            MLFLOW_TRACKING_URI=postgresql+psycopg2://mlflow_user:${{ secrets.DB_PASSWORD }}@/mlflow_db?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg
            ARTIFACT_BUCKET=${{ secrets.ARTIFACT_BUCKET }}

      - name: Deploy Prefect Agent
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: prefect-agent
          image: ${{ needs.auth-setup.outputs.registry_host }}/prefect/prefect-agent:latest
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account: github-actions-sa@mlops-461322.iam.gserviceaccount.com
          vpc_connector: vpc-connector
          cloud_sql_instances: ${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg
          env_vars: |
            PREFECT_ORION_API_URL=https://mlflow-server-${{ secrets.GCP_REGION }}.run.app
            PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect_user:${{ secrets.PREFECT_PASSWORD }}@/prefect_db?host=/cloudsql/${{ secrets.GCP_PROJECT }}:${{ secrets.GCP_REGION }}:mlflow-pg