name: Terraform

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'infra/**'
  #     - '.github/workflows/terraform.yml'
  workflow_dispatch: {}

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_prefect_db_password: ${{ secrets.PREFECT_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra
        run: terraform apply --auto-approve
